import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface PageProps {
  onBack: () => void;
}

export const TermsOfServicePage: React.FC<PageProps> = ({ onBack }) => {
  return (
    <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-12 animate-fade-in text-gray-200">
      {/* Back Button */}
      <button
        type="button"
        onClick={onBack}
        className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-gray-300 hover:text-white hover:border-[#F7DF1E] text-xs font-semibold transition-all mb-8 cursor-pointer shadow-2xs"
      >
        <ArrowLeft className="w-3.5 h-3.5" />
        <span>Back to Converter</span>
      </button>

      {/* Main Title */}
      <div className="border-b border-zinc-800 pb-6 mb-8">
        <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-3 text-base text-gray-400 leading-relaxed font-sans">
          Last updated: 2026 September. Simple, clear terms for using the json2js open community developer tool.
        </p>
      </div>

      {/* Flat Wikipedia-style Plain Text Content */}
      <div className="space-y-8 text-sm sm:text-base leading-relaxed text-gray-300">
        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight mb-3">
            1. Free &amp; Open for All Use Cases
          </h2>
          <p>
            json2js is distributed completely free of charge. You are free to use the tool for personal projects, academic research, commercial software development, open-source repositories, and enterprise applications without license fees or royalties.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight mb-3">
            2. Community-Driven Project
          </h2>
          <p>
            This tool operates as an independent community contribution. It is provided on a non-commercial basis to make JavaScript data manipulation simple and accessible to every programmer.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight mb-3">
            3. Intellectual Property of Converted Code
          </h2>
          <p>
            You retain 100% full and unrestricted ownership of any code, data structures, or objects generated by this converter. json2js and FireFolk claim no ownership, copyright, or intellectual property rights over your inputs or converted outputs.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight mb-3">
            4. Disclaimer of Warranty
          </h2>
          <p>
            The software is provided &ldquo;as is&rdquo;, without warranty of any kind, express or implied. While we take every effort to ensure accurate syntax generation and strict standard compliance, developers are responsible for testing and validating their code in their respective runtime environments.
          </p>
        </div>
      </div>
    </div>
  );
};
